title: "Mike Glass"
description: "Backend Software Engineer - Automation, Performance, Modernization"
baseurl: ""
url: "https://mglass2.github.io"

markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme