title: "UV Automation"
description: "I automate repetitive tasks to help small businesses run more efficiently."
baseurl: ""
url: "https://mglass2.github.io"

markdown: kramdown
theme: null
plugins: []