title: "Upper Valley Automation"
description: "I automate tasks to help small businesses run more efficiently."
baseurl: ""
url: "https://mglass2.github.io"

markdown: kramdown
theme: jekyll-theme-cayman
plugins: []