title: "Mike Glass"
description: "Backend Software Engineer - Automation, Performance, Modernization"
baseurl: ""
url: "https://mglass2.github.io"

markdown: kramdown
theme: jekyll-theme-cayman
plugins: []